{% set version = '1.11.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-data.table
  version: {{ version|replace("-", "_") }}

source:
  fn: data.table_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/data.table_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/data.table/data.table_{{ version }}.tar.gz
  sha256: 44f548517426c0444f7ce993bf93350be9f31e214d3dad39f9a680a53f9e6e64

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('data.table')"           # [not win]
    - "\"%R%\" -e \"library('data.table')\""  # [win]

about:
  home: http://r-datatable.com
  license: GPL-3
  license_file: LICENSE
  summary: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete
    of columns by group using no copies at all, list columns, a fast friendly file reader
    and parallel file writer. Offers a natural and flexible syntax, for faster development.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
