appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: ag3RB2jbX9XoZOgr/BgQ0JrHQHkgDk/o21akZ79dh7lHIpGrt7PXcMfzO4t565LgViPKMvuhN5OnVjIEqlEDMVmKwWdKNhHFif5ZmLxzo/zUCLaQpEcwvwWrptdiopv8VA4qbdG+Y3s/gFq29HX5xTyxZfCa3y+cl+06hKyqrblO3UZPYfbu4tgVRZINCvzhvm4bgf1S5n/WUYKr1/XA/sGgt2I0UYnOITxpR7Xn6azUd/yGy0ha6rWu7lq/QVYM4Vw8q4wW/DyF9uiPKJQTp77kATrkGWTYZV9qqdTxXD4exVQg8CDBlMSpAQM/vD5LU/tjsW6dZuIRt2dMlm2oJ9nZFl1k9rH4pPO8LN8XJb4yifZdsFpyst5Cfd+U9feelYNi4aOlFNasyWnWXFrJoA4Ybdv3LCflMQtnP+DXFGptEgjab3puFVdYcAzfP1ItWfhntBcp4XTa1deRePwDgiQjjYPvcRKKi4GssbnpFJvFaNStbovXIi90T1jsQ6/3yHEX54KywUlC9KQp7ky54g1wHQjAXqS7QEEGZYa1yrw7+iFx+rRGbAkQWaQ/lwir+l3zlVOUvC72W2MMPyPNyYzh6yLYs1GH8elO5cDgvhrng//ZwLJPZOkth/0E4ngqF7JxOaEkN/RosP/inMlEPIXoiwzH1sjstSgotaB/wrg=}
bot:
  automerge: true
